name: shopify_flutter
description: A flutter package that works as a bridge between your Shopify Store and Flutter Application.
version: 1.0.8
homepage: https://github.com/imsujan276/shopify_flutter

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.0.20
  intl: ^0.18.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  pedantic: ^1.11.1